[build]
command = "npm run generate"
publish = "dist"

[[redirects]]
  from = "/blog"
  to = "https://shreyaan.tech"
  status = 301
  force = true
  
[[redirects]]
  from = "/yt"
  to = "https://www.youtube.com/shreyaanvashishtha"
  status = 301
  force = true
  
[[redirects]]
  from = "/doter"
  to = "https://doter.cc"
  status = 301
  force = true
  
[[redirects]]
  from = "/forumic"
  to = "https://www.forumic.net"
  status = 301
  force = true
  
[[redirects]]
  from = "/yt"
  to = "https://www.youtube.com/shreyaanvashishtha"
  status = 301
  force = true
  
[[redirects]]
  from = "/yt_subscribe"
  to = "https://www.youtube.com/channel/UCyu1dpKpSsbKjSr5pT06Uuw?sub_confirmation=1"
  status = 301
  force = true
  
# [[plugins]]
# package = "netlify-plugin-subfont"
