[build]
command = "npm run generate"
publish = "dist"

[[redirects]]
  from = "/blog"
  to = "https://shreyaan.tech"
  status = 301
  force = true
  
[[redirects]]
  from = "/yt"
  to = "https://www.youtube.com/shreyaanvashishtha"
  status = 301
  force = true
  
[[redirects]]
  from = "/doter"
  to = "https://doter.cc"
  status = 301
  force = true
  
[[redirects]]
  from = "/forumic"
  to = "https://www.forumic.net"
  status = 301
  force = true
  
[[redirects]]
  from = "/yt"
  to = "https://www.youtube.com/shreyaanvashishtha"
  status = 301
  force = true
  
[[redirects]]
  from = "/yt_subscribe"
  to = "https://www.youtube.com/channel/UCyu1dpKpSsbKjSr5pT06Uuw?sub_confirmation=1"
  status = 301
  force = true
  
[[redirects]]
  from = "/github"
  to = "https://github.com/ShreyaanVashishtha"
  status = 301
  force = true
  
[[redirects]]
  from = "/git-org"
  to = "https://github.com/Shreyaan-Vashishtha"
  status = 301
  force = true
  
[[redirects]]
  from = "/after-effects-visualizer-file"
  to = "https://drive.google.com/file/d/13SGQ8lhVfensHa4vtTooBb0dIIkQs5uZ/view?usp=sharing"
  status = 301
  force = true
  
[[redirects]]
  from = "/buddyquiz"
  to = "https://buddymojo.com/match/dGr3"
  status = 301
  force = true
  
[[redirects]]
  from = "/top-screen-recorders_android"
  to = "https://www.shreyaan.tech/2021/04/10-best-screen-recording-apps-for.html"
  status = 301
  force = true

[[redirects]]
  from = "/ig"
  to = "https://www.instagram.com/shreyaanvashishtha/"
  status = 301
  force = true
  
 [[redirects]]
  from = "/discord"
  to = "https://discord.gg/m8uccSwb77"
  status = 301
  force = true
  
# [[plugins]]
# package = "netlify-plugin-subfont"
